#!/bin/bash
#SBATCH --job-name=prepack
#SBATCH --nodes=1
#SBATCH --nodelist=node001
#SBATCH --cpus-per-task=128
#SBATCH --output=/home/ld258/ipredict/slurm_logs/prepack-output-%j.out
#SBATCH --error=/home/ld258/ipredict/slurm_logs/prepack-error-%j.out
#SBATCH --mem=900G

module load miniconda/py39_4.12.0

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate fvlm

export PYTHONPATH=/home/ld258/ipredict/oracle-ct:$PYTHONPATH

# ==============================================================================
# CONFIGURATION
# ===========================================================================

IMAGE_ROOT="/scratch/railabs/ld258/dataset/AMOS_Abdomen/FLARE-Task4-CT-FM/val_downstream/abdomen_disease_classify/imagesTr/"
SEG_ROOT="/scratch/railabs/ld258/output/segmentation/AMOS_ABDOMEN/AMOS-SEGMENTATION/total/"
BODY_MASK_ROOT="/scratch/railabs/ld258/output/segmentation/AMOS_ABDOMEN/AMOS-SEGMENTATION/body/"
KIDNEY_CYST_ROOT="/scratch/railabs/ld258/output/segmentation/AMOS_ABDOMEN/AMOS-SEGMENTATION/kidney_cysts/"
OUTPUT_ROOT="/cachedata/ld258/AMOS/packs"

# ==============================================================================
# RUN
# ==============================================================================

python /home/ld258/ipredict/oracle-ct/oracle_ct/scripts/prepack.py\
    --image_root ${IMAGE_ROOT} \
    --seg_root ${SEG_ROOT} \
    --body_mask_root ${BODY_MASK_ROOT} \
    --kidney_cyst_root ${KIDNEY_CYST_ROOT} \
    --output_root ${OUTPUT_ROOT} \
    --target_spacing 1.5 1.5 3 \
    --target_shape 224 224 160 \
    --hu_min -1000 \
    --hu_max 1000 \
    --num_workers 96

    

    
