#!/bin/bash
#SBATCH --job-name=download_pillar
#SBATCH --nodes=1
#SBATCH --cpus-per-task=4
#SBATCH --output=/home/ld258/ipredict/slurm_logs/oracle-ct/download_pillar-output-%j.out
#SBATCH --error=/home/ld258/ipredict/slurm_logs/oracle-ct/download_pillar-error-%j.out

module load miniconda/py39_4.12.0
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate fvlm

export HF_TOKEN=$HUGGINGFACE_HUB_TOKEN

python /home/ld258/ipredict/oracle-ct/oracle_ct/scripts/download_pillar_model.py \
    --token $HF_TOKEN
